# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-01 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_release1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='public'),
        ),
    ]
