# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSupplementalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='title')),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
                ('paper', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Paper', verbose_name='paper')),
            ],
            options={
                'ordering': ('paper', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='paperauthorname',
            name='paper',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Paper', verbose_name='paper'),
        ),
        migrations.AlterField(
            model_name='paperkeyword',
            name='paper',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Paper', verbose_name='paper'),
        ),
        migrations.AlterUniqueTogether(
            name='papersupplementallink',
            unique_together=set([('url', 'paper'), ('name', 'paper')]),
        ),
    ]
