# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-12-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date posted')),
                ('date_changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date changed')),
                ('message', models.TextField(max_length=10000, verbose_name='message')),
                ('methodology', models.IntegerField(choices=[(-1, 'Questionable'), (0, 'Mixed'), (1, 'Rigorous')], help_text='Quality of methodology. If about half of the conclusions are invalid due to methodology errors, choose "Mixed".', verbose_name='methodology')),
                ('importance', models.IntegerField(choices=[(0, 'Waste of time'), (1, 'Average'), (2, 'Revolutionary')], help_text='How much attention this paper deserves, not just for its conclusions but also for new methodologies or any other revolutionary scientific ideas.', verbose_name='importance')),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='deleted')),
                ('paper', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.Paper', verbose_name='paper')),
                ('posted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person', verbose_name='posted by')),
            ],
            options={
                'ordering': ('paper', '-date_posted'),
            },
        ),
        migrations.CreateModel(
            name='PaperReviewResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date posted')),
                ('date_changed', models.DateTimeField(auto_now=True, db_index=True, verbose_name='date changed')),
                ('message', models.TextField(max_length=10000, verbose_name='message')),
                ('parent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.PaperReview', verbose_name='review')),
                ('posted_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Person', verbose_name='posted by')),
            ],
            options={
                'ordering': ('parent', '-date_posted'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='paperreview',
            unique_together=set([('paper', 'posted_by')]),
        ),
    ]
