# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-11 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paper_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='event date')),
                ('event_type', models.IntegerField(choices=[(0, '{person} has posted a new paper: {paper}'), (1, '{person} has confirmed authorship of {paper}'), (2, '{person} has posted a review of {paper}'), (3, '{person} recommends paper: {paper}')], db_index=True, editable=False, verbose_name='event type')),
                ('paper', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Paper', verbose_name='paper')),
                ('person', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
