# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-28 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.IntegerField(choices=[(0, 'New papers'), (1, 'Paper reviews'), (2, 'Recommendations')], db_index=True, editable=False, verbose_name='event type')),
                ('follower', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='person')),
                ('poster', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', related_query_name='follower', to='core.Person', verbose_name='person')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='feedsubscription',
            unique_together=set([('follower', 'subscription_type', 'poster')]),
        ),
    ]
