# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienceSubfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.IntegerField(choices=[(1, 'Astronomy'), (2, 'Biology'), (3, 'Chemistry'), (4, 'Computer Science'), (5, 'Earth Science'), (6, 'Engineering'), (7, 'History'), (8, 'Mathematics'), (9, 'Medicine'), (10, 'Philosophy'), (11, 'Physics'), (12, 'Social Science')], db_index=True, verbose_name='field')),
                ('name', models.CharField(help_text='Please enter only the English name of the subfield.', max_length=256, unique=True, verbose_name='name')),
            ],
            options={
                'ordering': ('field', 'name'),
            },
        ),
        migrations.AddField(
            model_name='paper',
            name='fields',
            field=models.ManyToManyField(to='core.ScienceSubfield'),
        ),
    ]
