# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sciencesubfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperImportSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=256, verbose_name='repository name')),
                ('import_cursor', models.CharField(max_length=128, verbose_name='import cursor')),
                ('bot_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='bot profile')),
            ],
        ),
    ]
