# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-22 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_textsearch_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/Prague', max_length=64, verbose_name='time zone'),
        ),
    ]
