# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-02-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperManagementDelegation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Person', verbose_name='author')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Person', verbose_name='delegate')),
            ],
            options={
                'ordering': ('author', 'delegate'),
            },
        ),
        migrations.AddField(
            model_name='person',
            name='paper_managers',
            field=models.ManyToManyField(related_name='delegating_authors', through='core.PaperManagementDelegation', to='core.Person'),
        ),
    ]
